# Site settings
title: Cosmo -Personal Blog
email: cosmo-loxp@gmail.com
description: A blog about managing social activities and with coding life and activities
baseurl: '/cosmo'
url: "http://blog.cosmo.com" # the base hostname & protocol for your site
facebook_username: loxporg
paginate: 3
# Build settings
markdown: kramdown
permalink: /:title

#Default settings

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts" # previously `post` in Jekyll 2.2.
    values:
      author: Sagaya Abdul
      layout: "post"
      comments: true
      title: Cosmo - {{post.title}}
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "pages" # previously `post` in Jekyll 2.2.
    values:
      layout: "page"
      